#! /usr/bin/python
import time
import threading
from subprocess import call, check_output
from random import randint

ip = "192.168.152.140"

numThreads = [0,1]
lock = threading.RLock()

def client(num):
    global ip
    call(["wget",ip,"-a","output.txt","-O","files/file_"+str(time.time())])
    update(num,-1)
    return

def update(num,value):
    lock.acquire()
    try:
        num[0]+=value
    finally:
        lock.release()

def manageClients(cliSec, numT):
    for j in range(20):
        for i in range(cliSec):
            t = threading.Thread(target=client, args=(numT,))
            t.start()
            update(numT,1)
            time.sleep(1.0/cliSec)
    numT[1] = 0

def reporter(numT, rr):
    #for i in range(20):
    while numT[1] == 1 or numT[0] > 0:
        time.sleep(rr)
        out = check_output(['du','-h','files'])
        print "Data: "+out
        print "N- Threads: %s" % numT[0]

manager = threading.Thread(target=manageClients, args=(8,numThreads,))
report  = threading.Thread(target=reporter, args=(numThreads,1,))
manager.start()
report.start()
