#! /usr/bin/python 
"""
Send a GET request::
    curl http://localhost

Send a HEAD request::
    curl -I http://localhost

Send a POST request::
    curl -d "foo=bar&bin=baz" http://localhost
"""

from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
from subprocess import call
from random import randint
import time
import SocketServer

class S(BaseHTTPRequestHandler):
    def _set_headers(self):
        self.send_response(200)
        self.send_header('Content-type', 'application/octet-stream')
        self.end_headers()

    def do_GET(self):
	list=["512K","1M","2M","4M","16M","32M","64M"]
        self._set_headers()
	i = randint(1, 7)
	filename = "file_"+str(time.time()) 
	call(["dd","if=/dev/urandom","of="+filename,"bs="+list[i],"count=1"]) 
	f = open(filename, 'rb')
	while True:
		data = f.read(4096)
		if data is None or len(data) == 0:
			break
        	self.wfile.write(data)
	f.close()
	call(["rm","-f",filename])

    def do_HEAD(self):
        self._set_headers()
        
    def do_POST(self):
        # Doesn't do anything with posted data
        self._set_headers()
        self.wfile.write("<html><body><h1>POST!</h1></body></html>")
        
def run(server_class=HTTPServer, handler_class=S, port=80):
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    print 'Starting httpd...'
    httpd.serve_forever()

if __name__ == "__main__":
    from sys import argv
    if len(argv) == 2:
        run(port=int(argv[1]))
    else:
        run()
