cli: client
	rm -rf files/*
	rm -rf output.txt
	./client 1
	mv resultData_1.csv resultThreads_1.csv graphs/maq3-16mb
	rm -rf files/*
	rm -rf output.txt
	./client 2
	mv resultData_2.csv resultThreads_2.csv graphs/maq3-16mb
	rm -rf files/*
	rm -rf output.txt
	./client 5
	mv resultData_5.csv resultThreads_5.csv graphs/maq3-16mb
	rm -rf files/*
	rm -rf output.txt
	./client 10
	mv resultData_10.csv resultThreads_10.csv graphs/maq3-16mb
